# install the `pacman` package manager
#install.packages("pacman")
library("pacman")

# Install and/or Load Commonly Used Packages
p_load("renv")
p_load("tidyverse")
p_load("ggthemes")
p_load("ggpubr")
p_load("ggfittext")
p_load("ggsci")
p_load("viridis")
p_load("scales")
p_load("knitr")
p_load("magrittr")
p_load("stringi")
p_load("rio")
p_load("openxlsx")
p_load("hms")
p_load("styler")
p_load("lintr")
p_load("openxlsx")
